import { Container, Paper, Typography } from "@mui/material";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import apiClient from "../../../apiClient";

export default function Meetings(){
    const router = useRouter();
    const [rooms,setRooms] = useState([])
    //console.log(router)

    useEffect(() => {
        if(router.query.slug){
        apiClient.get(`/api/rooms/${router.query.slug}`)
        .then((response) => {
            //console.log(response.data)
            //alert('si conecto');
            setRooms(response.data)
        })
        .catch((error) => {
            alert("Error al visualizar el componente, intente más tarde")
        });
        }
    }, [router]);

    console.log(rooms)
    return (
        <>
        <Head>
            <title>Componentes</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>


        <Paper>
        <h1>Informacion del componente</h1>
        
    <Container>
    </Container>
    </Paper>

</>
    )
}